version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./share/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_DATABASE: metastore
      MYSQL_ROOT_PASSWORD: root
    container_name: cloudera_mysql
    networks:
      - cloudera-net
  centos8:
    image: centos:8
    platform: linux/amd64
    command: sleep infinity
    container_name: centos8
    networks:
      - cloudera-net

networks:
  cloudera-net:
    driver: bridge
